
import java.awt.Color;
import javax.swing.JFrame;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author DELL
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    Color DefaultColor, ClickedColor;

    public Dashboard() {
        initComponents();
        this.setLocationRelativeTo(null);
        DefaultColor = new Color(248, 221, 114);
        ClickedColor = new Color(252, 191, 74);

        //set default color to pan on run time
        btnto_beranda.setBackground(DefaultColor);
        btnto_formkasir.setBackground(DefaultColor);
        btnto_databarang.setBackground(DefaultColor);
        btnto_datasewaan.setBackground(DefaultColor);
        btnto_laporan.setBackground(DefaultColor);
        btnto_pengguna.setBackground(DefaultColor);
        btnto_formpengembalian.setBackground(DefaultColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        MenuName = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        SubMenu = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        btn_logout = new javax.swing.JLabel();
        btnto_beranda = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnto_formkasir = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnto_databarang = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnto_datasewaan = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnto_laporan = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnto_pengguna = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btnto_formpengembalian = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        img_dashboard = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(252, 191, 74));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Pesanan Berlangsung");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 200, 80));

        jPanel2.setBackground(new java.awt.Color(252, 191, 74));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Pesanan Selesai");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 200, 80));

        jPanel3.setBackground(new java.awt.Color(252, 191, 74));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Total Transaksi");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 170, 200, 80));

        jPanel4.setBackground(new java.awt.Color(252, 191, 74));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Total Pesanan");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 170, 200, 80));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        MenuName.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        MenuName.setText("Beranda");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(MenuName)
                .addContainerGap(352, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(MenuName)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 530, 80));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        SubMenu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SubMenu.setForeground(new java.awt.Color(102, 102, 102));
        SubMenu.setText("Home / Beranda");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SubMenu)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(SubMenu)
                .addContainerGap())
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 150, 30));

        jPanel7.setBackground(new java.awt.Color(252, 191, 74));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Awan Advanture");

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/299525419_127456876680601_7892286217951910501_n 3.png"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel4))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel20)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(13, 13, 13))
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 130));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        btn_logout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(255, 51, 51));
        btn_logout.setText("Logout");
        btn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_logoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(212, Short.MAX_VALUE)
                .addComponent(btn_logout)
                .addGap(18, 18, 18))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(btn_logout)
                .addGap(29, 29, 29))
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 0, 280, 80));

        btnto_beranda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnto_berandaMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Beranda");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_home_25px_1.png"))); // NOI18N

        javax.swing.GroupLayout btnto_berandaLayout = new javax.swing.GroupLayout(btnto_beranda);
        btnto_beranda.setLayout(btnto_berandaLayout);
        btnto_berandaLayout.setHorizontalGroup(
            btnto_berandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnto_berandaLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnto_berandaLayout.setVerticalGroup(
            btnto_berandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(btnto_beranda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 200, 50));

        btnto_formkasir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnto_formkasirMousePressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Form Kasir");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_shopping_cart_25px.png"))); // NOI18N

        javax.swing.GroupLayout btnto_formkasirLayout = new javax.swing.GroupLayout(btnto_formkasir);
        btnto_formkasir.setLayout(btnto_formkasirLayout);
        btnto_formkasirLayout.setHorizontalGroup(
            btnto_formkasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnto_formkasirLayout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnto_formkasirLayout.setVerticalGroup(
            btnto_formkasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addGroup(btnto_formkasirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(btnto_formkasir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 200, -1));

        btnto_databarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnto_databarangMousePressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Data Barang");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_open_box_25px.png"))); // NOI18N

        javax.swing.GroupLayout btnto_databarangLayout = new javax.swing.GroupLayout(btnto_databarang);
        btnto_databarang.setLayout(btnto_databarangLayout);
        btnto_databarangLayout.setHorizontalGroup(
            btnto_databarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnto_databarangLayout.createSequentialGroup()
                .addGap(0, 21, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnto_databarangLayout.setVerticalGroup(
            btnto_databarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addGroup(btnto_databarangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(btnto_databarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 200, -1));

        btnto_datasewaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnto_datasewaanMousePressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Data Sewaan");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_land_sales_25px_3.png"))); // NOI18N

        javax.swing.GroupLayout btnto_datasewaanLayout = new javax.swing.GroupLayout(btnto_datasewaan);
        btnto_datasewaan.setLayout(btnto_datasewaanLayout);
        btnto_datasewaanLayout.setHorizontalGroup(
            btnto_datasewaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnto_datasewaanLayout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnto_datasewaanLayout.setVerticalGroup(
            btnto_datasewaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addGroup(btnto_datasewaanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(btnto_datasewaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 200, -1));

        btnto_laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnto_laporanMousePressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Laporan");

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_edit_pie_chart_report_25px.png"))); // NOI18N

        javax.swing.GroupLayout btnto_laporanLayout = new javax.swing.GroupLayout(btnto_laporan);
        btnto_laporan.setLayout(btnto_laporanLayout);
        btnto_laporanLayout.setHorizontalGroup(
            btnto_laporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnto_laporanLayout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnto_laporanLayout.setVerticalGroup(
            btnto_laporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addGroup(btnto_laporanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(btnto_laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 200, -1));

        btnto_pengguna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnto_penggunaMousePressed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Pengguna");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_customer_25px.png"))); // NOI18N

        javax.swing.GroupLayout btnto_penggunaLayout = new javax.swing.GroupLayout(btnto_pengguna);
        btnto_pengguna.setLayout(btnto_penggunaLayout);
        btnto_penggunaLayout.setHorizontalGroup(
            btnto_penggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnto_penggunaLayout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnto_penggunaLayout.setVerticalGroup(
            btnto_penggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addGroup(btnto_penggunaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(btnto_pengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 200, -1));

        btnto_formpengembalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnto_formpengembalianMousePressed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Form Pengembalian");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_receive_cash_25px_1.png"))); // NOI18N

        javax.swing.GroupLayout btnto_formpengembalianLayout = new javax.swing.GroupLayout(btnto_formpengembalian);
        btnto_formpengembalian.setLayout(btnto_formpengembalianLayout);
        btnto_formpengembalianLayout.setHorizontalGroup(
            btnto_formpengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnto_formpengembalianLayout.createSequentialGroup()
                .addGap(0, 21, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14))
        );
        btnto_formpengembalianLayout.setVerticalGroup(
            btnto_formpengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addGroup(btnto_formpengembalianLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(btnto_formpengembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 200, -1));

        img_dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Dashboard (3) 1.png"))); // NOI18N
        img_dashboard.setText("  ");
        getContentPane().add(img_dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_btn_logoutMouseClicked

    private void btnto_berandaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnto_berandaMousePressed
        // TODO add your handling code here:
        btnto_beranda.setBackground(ClickedColor);
        btnto_formkasir.setBackground(DefaultColor);
        btnto_databarang.setBackground(DefaultColor);
        btnto_datasewaan.setBackground(DefaultColor);
        btnto_laporan.setBackground(DefaultColor);
        btnto_pengguna.setBackground(DefaultColor);
        btnto_formpengembalian.setBackground(DefaultColor);
        
        MenuName.setText("Beranda");
        SubMenu.setText("Home / Beranda");
    }//GEN-LAST:event_btnto_berandaMousePressed

    private void btnto_formkasirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnto_formkasirMousePressed
        // TODO add your handling code here:
        btnto_beranda.setBackground(DefaultColor);
        btnto_formkasir.setBackground(ClickedColor);
        btnto_databarang.setBackground(DefaultColor);
        btnto_datasewaan.setBackground(DefaultColor);
        btnto_laporan.setBackground(DefaultColor);
        btnto_pengguna.setBackground(DefaultColor);
        btnto_formpengembalian.setBackground(DefaultColor);
        
        MenuName.setText("Form asir");
        SubMenu.setText("Home / Kasir");
    }//GEN-LAST:event_btnto_formkasirMousePressed

    private void btnto_databarangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnto_databarangMousePressed
        // TODO add your handling code here:
        btnto_beranda.setBackground(DefaultColor);
        btnto_formkasir.setBackground(DefaultColor);
        btnto_databarang.setBackground(ClickedColor);
        btnto_datasewaan.setBackground(DefaultColor);
        btnto_laporan.setBackground(DefaultColor);
        btnto_pengguna.setBackground(DefaultColor);
        btnto_formpengembalian.setBackground(DefaultColor);
        
        MenuName.setText("Data Barang");
        SubMenu.setText("Home / Barang");
    }//GEN-LAST:event_btnto_databarangMousePressed

    private void btnto_datasewaanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnto_datasewaanMousePressed
        // TODO add your handling code here:
        btnto_beranda.setBackground(DefaultColor);
        btnto_formkasir.setBackground(DefaultColor);
        btnto_databarang.setBackground(DefaultColor);
        btnto_datasewaan.setBackground(ClickedColor);
        btnto_laporan.setBackground(DefaultColor);
        btnto_pengguna.setBackground(DefaultColor);
        btnto_formpengembalian.setBackground(DefaultColor);
        
        MenuName.setText("Data Sewaan");
        SubMenu.setText("Home / Sewaan");
    }//GEN-LAST:event_btnto_datasewaanMousePressed

    private void btnto_laporanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnto_laporanMousePressed
        // TODO add your handling code here:
        btnto_beranda.setBackground(DefaultColor);
        btnto_formkasir.setBackground(DefaultColor);
        btnto_databarang.setBackground(DefaultColor);
        btnto_datasewaan.setBackground(DefaultColor);
        btnto_laporan.setBackground(ClickedColor);
        btnto_pengguna.setBackground(DefaultColor);
        btnto_formpengembalian.setBackground(DefaultColor);
        
        MenuName.setText("Laporan");
        SubMenu.setText("Home / Laporan");
    }//GEN-LAST:event_btnto_laporanMousePressed

    private void btnto_penggunaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnto_penggunaMousePressed
        // TODO add your handling code here:
        btnto_beranda.setBackground(DefaultColor);
        btnto_formkasir.setBackground(DefaultColor);
        btnto_databarang.setBackground(DefaultColor);
        btnto_datasewaan.setBackground(DefaultColor);
        btnto_laporan.setBackground(DefaultColor);
        btnto_pengguna.setBackground(ClickedColor);
        btnto_formpengembalian.setBackground(DefaultColor);
        
        MenuName.setText("Pengguna");
        SubMenu.setText("Home / Pengguna");
    }//GEN-LAST:event_btnto_penggunaMousePressed

    private void btnto_formpengembalianMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnto_formpengembalianMousePressed
        // TODO add your handling code here:
        btnto_beranda.setBackground(DefaultColor);
        btnto_formkasir.setBackground(DefaultColor);
        btnto_databarang.setBackground(DefaultColor);
        btnto_datasewaan.setBackground(DefaultColor);
        btnto_laporan.setBackground(DefaultColor);
        btnto_pengguna.setBackground(DefaultColor);
        btnto_formpengembalian.setBackground(ClickedColor);
        
        MenuName.setText("Form Pengembalian");
        SubMenu.setText("Home / Pengembalian");
    }//GEN-LAST:event_btnto_formpengembalianMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MenuName;
    private javax.swing.JLabel SubMenu;
    private javax.swing.JLabel btn_logout;
    private javax.swing.JPanel btnto_beranda;
    private javax.swing.JPanel btnto_databarang;
    private javax.swing.JPanel btnto_datasewaan;
    private javax.swing.JPanel btnto_formkasir;
    private javax.swing.JPanel btnto_formpengembalian;
    private javax.swing.JPanel btnto_laporan;
    private javax.swing.JPanel btnto_pengguna;
    private javax.swing.JLabel img_dashboard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
}
