/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import koneksi.Connect;
import java.sql.*;
import javax.swing.JOptionPane;
import com.mysql.cj.jdbc.Driver;
/**
 *
 * @author perlengkapan
 */
public class ForgetPassword extends javax.swing.JFrame {

    /**
     * Creates new form ForgetPassword
     */
    public ForgetPassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_username = new javax.swing.JTextField();
        txt_pin = new javax.swing.JTextField();
        txt_newPass = new javax.swing.JPasswordField();
        checkPass = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        btn_reset = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        txt_username.setBackground(new java.awt.Color(255, 255, 255));
        txt_username.setFont(new java.awt.Font("Outfit", 0, 20)); // NOI18N
        txt_username.setForeground(new java.awt.Color(0, 0, 0));
        txt_username.setBorder(null);
        getContentPane().add(txt_username);
        txt_username.setBounds(730, 276, 330, 20);

        txt_pin.setBackground(new java.awt.Color(255, 255, 255));
        txt_pin.setFont(new java.awt.Font("Outfit", 0, 20)); // NOI18N
        txt_pin.setForeground(new java.awt.Color(0, 0, 0));
        txt_pin.setBorder(null);
        getContentPane().add(txt_pin);
        txt_pin.setBounds(730, 370, 320, 20);

        txt_newPass.setBackground(new java.awt.Color(255, 255, 255));
        txt_newPass.setFont(new java.awt.Font("Outfit", 0, 20)); // NOI18N
        txt_newPass.setForeground(new java.awt.Color(0, 0, 0));
        txt_newPass.setBorder(null);
        getContentPane().add(txt_newPass);
        txt_newPass.setBounds(730, 464, 330, 20);

        checkPass.setBackground(new java.awt.Color(255, 255, 255));
        checkPass.setForeground(new java.awt.Color(0, 0, 0));
        checkPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPassActionPerformed(evt);
            }
        });
        getContentPane().add(checkPass);
        checkPass.setBounds(720, 500, 20, 19);

        jLabel2.setFont(new java.awt.Font("Outfit", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Show Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(740, 500, 100, 18);

        btn_reset.setBackground(new java.awt.Color(252, 191, 73));
        btn_reset.setFont(new java.awt.Font("Outfit", 0, 21)); // NOI18N
        btn_reset.setForeground(new java.awt.Color(0, 0, 0));
        btn_reset.setText("Reset Password");
        btn_reset.setBorder(null);
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        getContentPane().add(btn_reset);
        btn_reset.setBounds(700, 560, 380, 60);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(680, 550, 410, 70);

        jLabel1.setFont(new java.awt.Font("Outfit", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Sudah punya akun ?");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(800, 630, 130, 18);

        jLabel3.setFont(new java.awt.Font("Outfit", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 133, 255));
        jLabel3.setText("Login");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(930, 630, 37, 16);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/forgetPassword.jpg"))); // NOI18N
        getContentPane().add(bg);
        bg.setBounds(0, 0, 1280, 720);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        try{
            if(txt_username.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Username tidak boleh kosong");
                txt_username.requestFocus();
            }else if(txt_pin.getText().equals("")){
                JOptionPane.showMessageDialog(null, "PIN tidak boleh kosong");
                txt_pin.requestFocus();
            }else if(txt_newPass.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Password tidak boleh kosong");
                txt_newPass.requestFocus();
            }else{
                Connection conn = Connect.GetConnection();
                String sql = "SELECT * FROM pengguna WHERE username = ? AND pin = ?";
                PreparedStatement st = conn.prepareStatement(sql);
                st.setString(1, txt_username.getText());
                st.setString(2, txt_pin.getText());
                ResultSet rs = st.executeQuery();
                rs.next();
                PreparedStatement pst = conn.prepareStatement("UPDATE pengguna SET password = ? WHERE id_pengguna = ?");
                pst.setString(1, txt_newPass.getText());
                pst.setString(2, rs.getString("id_pengguna"));
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Password berhasil diperbarui, silahkan login", "Success", JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
                new Login().setVisible(true);
            }  
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Username atau PIN salah", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_resetActionPerformed

    private void checkPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPassActionPerformed
        // TODO add your handling code here:
        if(checkPass.isSelected()){
            txt_newPass.setEchoChar((char)0);
        }else{
            txt_newPass.setEchoChar('*');
        }
    }//GEN-LAST:event_checkPassActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgetPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btn_reset;
    private javax.swing.JCheckBox checkPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txt_newPass;
    private javax.swing.JTextField txt_pin;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
