/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import com.mysql.cj.jdbc.Driver;
import java.sql.*;
import javax.swing.JOptionPane;
import koneksi.Connect;
/**
 *
 * @author perlengkapan
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_username = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        btn_login = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lupaPassword = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        checkPass = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(242, 242, 242));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        txt_username.setBackground(new java.awt.Color(255, 255, 255));
        txt_username.setFont(new java.awt.Font("Outfit", 0, 20)); // NOI18N
        txt_username.setBorder(null);
        getContentPane().add(txt_username);
        txt_username.setBounds(730, 340, 330, 20);

        txt_password.setBackground(new java.awt.Color(255, 255, 255));
        txt_password.setFont(new java.awt.Font("Outfit", 0, 20)); // NOI18N
        txt_password.setBorder(null);
        getContentPane().add(txt_password);
        txt_password.setBounds(730, 436, 330, 20);

        btn_login.setBackground(new java.awt.Color(252, 191, 73));
        btn_login.setFont(new java.awt.Font("Outfit", 0, 21)); // NOI18N
        btn_login.setForeground(new java.awt.Color(0, 0, 0));
        btn_login.setText("Login");
        btn_login.setBorder(null);
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        getContentPane().add(btn_login);
        btn_login.setBounds(700, 560, 380, 50);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lupaPassword.setBackground(new java.awt.Color(255, 255, 255));
        lupaPassword.setFont(new java.awt.Font("Outfit", 0, 21)); // NOI18N
        lupaPassword.setForeground(new java.awt.Color(0, 133, 255));
        lupaPassword.setText("Lupa Password?");
        lupaPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lupaPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lupaPasswordMouseClicked(evt);
            }
        });
        jPanel1.add(lupaPassword);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(890, 520, 220, 30);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel2);
        jPanel2.setBounds(680, 550, 410, 70);

        checkPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPassActionPerformed(evt);
            }
        });
        getContentPane().add(checkPass);
        checkPass.setBounds(720, 470, 20, 19);

        jLabel3.setFont(new java.awt.Font("Outfit", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Show Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(740, 470, 110, 18);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loginPage.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1280, 720);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // TODO add your handling code here:
        try{
            if(txt_username.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Username tidak boleh kosong", "Warning", JOptionPane.WARNING_MESSAGE);
                txt_username.requestFocus();
            }else if(txt_password.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Password tidak boleh kosong", "Warning", JOptionPane.WARNING_MESSAGE);
                txt_password.requestFocus();
            }else{
                java.sql.Connection conn = (Connection)Connect.GetConnection();
                String sql = "SELECT * FROM pengguna WHERE username ='"+txt_username.getText()+"' AND password = '"+ txt_password.getText()+"'";
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
//                pst.setString(1, );
//                pst.setString(2, );
                java.sql.ResultSet rs = pst.executeQuery(sql);

                if(rs.next()){
                    if(txt_username.getText().equals(rs.getString("username"))){
                        JOptionPane.showMessageDialog(null, "berhasil login");
                        this.setVisible(false);
                        Dashboard dashboard = new Dashboard();
                        dashboard.getAcc(rs.getString("nama"), rs.getString("hak_akses"));
                        dashboard.setVisible(true);
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Username atau Password salah");
                    txt_username.requestFocus();
                }
            }
        }catch(Exception e){
          JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btn_loginActionPerformed

    private void checkPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPassActionPerformed
        // TODO add your handling code here:
        if(checkPass.isSelected()){
            txt_password.setEchoChar((char)0);
        }else{
            txt_password.setEchoChar('*');
        }
    }//GEN-LAST:event_checkPassActionPerformed

    private void lupaPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lupaPasswordMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new ForgetPassword().setVisible(true);
    }//GEN-LAST:event_lupaPasswordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);   
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JCheckBox checkPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lupaPassword;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
